# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = '$username$directory$character'
right_format = '$status$git_status$git_branch$container$hostname'

[character]
format = '[❯ ](#FF0066)'

[package]
disabled = false

[username]
show_always = true
format = '[$user]($style)'
style_user = 'bold #FF0066'
style_root = 'bold #A00CE8'

[hostname]
ssh_only = true
style = 'bold blue'
format = '[ $hostname]($style)'

[container]
style = 'dimmed white'
format = '[ $name](style)'

[status]
style = 'bold red'
symbol = ' '
sigint_symbol = ' '
not_found_symbol = ''
signal_symbol = ''
format = '[$symbol]($style) '
map_symbol = true
disabled = false

[directory]
truncation_length = 3
truncation_symbol = '…/'
style = 'cyan'
format = ' [$path]($style)[$read_only]($read_only_style) '

[git_branch]
disabled = false
symbol = ''
style = 'bold dimmed green'
format = '[$symbol $branch]($style)'
truncation_length = 4
# ignore_branches = ['master', 'main']

[git_status]
style = 'bold green'

[git_commit]
disabled = true

[git_state]
disabled = true
